version: 0.2

env:
  variables:
    HUGO_VERSION: "0.119.0"
    
phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_linux-amd64.tar.gz
      - mv hugo /usr/bin/hugo
      - cd -
      - rm -rf /tmp/*
  build:
    commands:
      - pwd
      - git submodule init -- themes/ananke
      - ls -al themes/ananke
      - rm -rf public
      - hugo
      - hugo deploy
  post_build:
    commands:
      - echo Build completed on `date`